services:
  - type: web
    name: gestion-proyecto-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://gestion-proyecto-backend.onrender.com
