# Generated by Django 4.2.7 on 2025-09-06 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del proyecto', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del proyecto')),
                ('status', models.CharField(choices=[('planning', 'Planificación'), ('active', 'Activo'), ('on_hold', 'En Pausa'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='planning', help_text='Estado actual del proyecto', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', help_text='Prioridad del proyecto', max_length=10)),
                ('start_date', models.DateField(help_text='Fecha de inicio del proyecto')),
                ('end_date', models.DateField(blank=True, help_text='Fecha de finalización estimada', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Propietario del proyecto', on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la tarea', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la tarea')),
                ('status', models.CharField(choices=[('todo', 'Por Hacer'), ('in_progress', 'En Progreso'), ('review', 'En Revisión'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='todo', help_text='Estado actual de la tarea', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', help_text='Prioridad de la tarea', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, help_text='Fecha límite de la tarea', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Fecha de finalización de la tarea', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Usuario asignado a la tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Usuario que creó la tarea', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Proyecto al que pertenece la tarea', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Gerente'), ('developer', 'Desarrollador'), ('designer', 'Diseñador'), ('tester', 'Probador'), ('observer', 'Observador')], default='observer', help_text='Rol del usuario en el proyecto', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Proyecto al que pertenece el miembro', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(help_text='Usuario miembro del proyecto', on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de Proyecto',
                'verbose_name_plural': 'Miembros de Proyecto',
                'db_table': 'project_members',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
