# Generated by Django 4.2.7 on 2025-09-06 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_alter_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmember',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Miembro de Proyecto', 'verbose_name_plural': 'Miembros de Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comentario de Tarea', 'verbose_name_plural': 'Comentarios de Tareas'},
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Fecha de finalización del proyecto', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(help_text='Usuario propietario del proyecto', on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('member', 'Miembro'), ('lead', 'Líder')], default='member', help_text='Rol del usuario en el proyecto', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(help_text='Usuario asignado a la tarea', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de completado de la tarea', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Fecha límite para completar la tarea', null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('task_assigned', 'Tarea Asignada'), ('task_completed', 'Tarea Completada'), ('project_assigned', 'Proyecto Asignado'), ('comment_added', 'Comentario Agregado')], help_text='Tipo de notificación', max_length=20)),
                ('title', models.CharField(help_text='Título de la notificación', max_length=200)),
                ('message', models.TextField(help_text='Mensaje de la notificación')),
                ('is_read', models.BooleanField(default=False, help_text='Indica si la notificación ha sido leída')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, help_text='Proyecto relacionado (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('task', models.ForeignKey(blank=True, help_text='Tarea relacionada (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.task')),
                ('user', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
