# Generated by Django 4.2.7 on 2025-09-07 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Indica si la notificación ha sido leída'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(help_text='Mensaje de la notificación'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyecto relacionado (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Tarea relacionada (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.task'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(help_text='Título de la notificación', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Tarea Asignada'), ('task_completed', 'Tarea Completada'), ('project_assigned', 'Proyecto Asignado'), ('comment_added', 'Comentario Agregado')], help_text='Tipo de notificación', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
